version: "3.7"
services:
    reservations:
        image: jeffrygonzalez/library-reservation-processor-nov-2020:latest
        depends_on: 
            - api 
            - rabbit
        restart: on-failure
        environment: 
            - apiUrl=http://api
            - Rabbit:HostName=rabbit
            - Rabbit:UserName=guest
            - Rabbit:Password=guest
            - Rabbit:Port=5672
            - Rabbit:VHost=/
        networks: 
            - my-network
    api:
        image: jeffrygonzalez/library-api-nov-2020:latest
        ports:
            - 80:80
        environment: 
            - Rabbit:HostName=rabbit
            - Rabbit:UserName=guest
            - Rabbit:Password=guest
            - Rabbit:Port=5672
            - Rabbit:VHost=/
            - ConnectionStrings__redis=redis
            - ConnectionStrings__library=server=sql;user=sa;password=TokyoJoe138!;database=books
        networks: 
            - my-network
    sql:
        image: jeffrygonzalez/sql-library-nov-2020:prod
        ports:
            - 1433:1433
        networks:
            - my-network
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - my-network
    rabbit:
        image: rabbitmq:3.8.9-management
        ports:
            - 15671:15671
            - 15672:15672
            - 5672:5672
        networks:
            - my-network
networks: 
    my-network:
        driver: bridge
