version: "3.7"
services:
    sql:
        image: jeffrygonzalez/sql-library-nov-2020:latest
        ports:
            - 1433:1433
    redis:
        image: redis:latest
        ports:
            - 6379:6379
