version: "3.7"
services:
    sql:
        image: jeffrygonzalez/sql-library-nov-2020:latest
        ports:
            - 1433:1433
    redis:
        image: redis:latest
        ports:
            - 6379:6379
    rabbit:
        image: rabbitmq:3.8.9-management
        ports:
            - 15671:15671
            - 15672:15672
            - 5672:5672
